project:
  type: website

website:
  title: "TidyTuesday"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    logo: images\pandas.png
  favicon:  images\pandas.png

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

